version: '3.8'
services:
  smartcity-app:
    build: .
    container_name: smartcity_app
    restart: always
    ports:
      - 8080:8080
    environment:
      DATABASE_URI: jdbc:mysql://mysqldb:3306/smartcity_project?createDatabaseIfNotExist=true
      DATABASE_USER: root
      DATABASE_PASSWORD: ez7mz
    depends_on:
      - mysqldb

  mysqldb:
    platform: linux/x86_64
    image: mysql:latest
    container_name: mysqldb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ez7mz

  maildev:
    image: maildev/maildev
    container_name: maildev
    ports:
      - 1080:1080
      - 1025:1025